dashevo/dapi-grpc

package-lock.json
package.json
tx-filter-stream/node/TransactionsFilterStreamClient.js

node client's `getTransactionsByFilter` doesn't return any value
Add return to the to `getTransactionsByFilter`

Fix Node.JS client no return

---

package-lock.json
package.json

A PR to trigger tagged build in Travis

Update library version to `0.9.4`

---

clients/java/org/dash/platform/dapi/v0/CoreGrpc.java
clients/nodejs/CorePromiseClient.js
clients/objective-c/Core.pbobjc.h
clients/objective-c/Core.pbobjc.m
clients/objective-c/Core.pbrpc.h
clients/objective-c/Core.pbrpc.m
package-lock.json
package.json
protos/core.proto
test/unit/clients/nodejs/CorePromiseClient.spec.js
test/unit/getCoreDefinition.spec.js

Fix `getStatus` response
New `getEstimatedTransactionFee` method
Added missed tests
Bump version

fix: core services

---

package-lock.json
package.json

Just updating version.
Version is updated to `0.14.0-dev.1`
Not required.
None.

chore: update version to 0.14.0-dev.1

---

package-lock.json
package.json

Update gRPC-Web to 1.2.0 version in order to mitigate stream connection issues.
`grpc-web` dependency updated to 1.2.0 version
With tests
None

feat: update gRPC-Web to 1.2.0 version

---

node.js

Get service definition functions export under the version namespace
Get service definition moved to the root of export
With tests
None

fix: get service definition under version namespace

---

clients/platform/v0/java/org/dash/platform/dapi/v0/PlatformGrpc.java
clients/platform/v0/nodejs/PlatformPromiseClient.js
clients/platform/v0/objective-c/Platform.pbobjc.h
clients/platform/v0/objective-c/Platform.pbobjc.m
clients/platform/v0/objective-c/Platform.pbrpc.h
clients/platform/v0/objective-c/Platform.pbrpc.m
clients/platform/v0/python/platform_pb2.py
clients/platform/v0/python/platform_pb2_grpc.py
protos/platform/v0/platform.proto

Added `getIdentitiesByPublicKeyHashes` and `getIdentityIdsByPublicKeyHashes` methods
Added `getIdentitiesByPublicKeyHashes` and `getIdentityIdsByPublicKeyHashes` methods
None.

feat: add `getIdentitiesByPublicKeyHashes` and `getIdentityIdsByPublicKeyHashes` methods

---

package-lock.json
package.json

chore: bump version to `0.16.0-dev.1`

---

clients/platform/v0/objective-c/Platform.pbobjc.h
clients/platform/v0/objective-c/Platform.pbobjc.m
clients/platform/v0/python/platform_pb2.py
protos/platform/v0/platform.proto

Identifiers which are binary hashes used as strings in protobuf messages.
- Use bytes to describe identifiers in protobuf messages.
None.
- `GetDataContractRequest`, `GetDocumentsRequest`, `GetIdentityRequest` now accepts bytes

feat!: use bytes for identifiers

---

package-lock.json
package.json

`protobufjs` converts object with empty Buffer to undefined for repeated bytes
Used fixed version of `protobuf`
Local script with serialization and deserialization
None.

fix: protobuf.js converts empty Buffer to undefined

---

clients/platform/v0/objective-c/Platform.pbobjc.h
clients/platform/v0/objective-c/Platform.pbobjc.m
clients/platform/v0/python/platform_pb2.py
protos/platform/v0/platform.proto

Need to provide proofs for platform responses.
Added new `prove` parameter in platform requests, new `proof` parameter in platform responses.

feat: add proofs to platform responses

---

clients/platform/v0/java/org/dash/platform/dapi/v0/PlatformGrpc.java
clients/platform/v0/nodejs/PlatformPromiseClient.js
clients/platform/v0/objective-c/Platform.pbobjc.h
clients/platform/v0/objective-c/Platform.pbobjc.m
clients/platform/v0/objective-c/Platform.pbrpc.h
clients/platform/v0/objective-c/Platform.pbrpc.m
clients/platform/v0/python/platform_pb2.py
clients/platform/v0/python/platform_pb2_grpc.py
protos/platform/v0/platform.proto

Added subscribeToStateTransitionResults streaming endpoint
No

feat: add subscribeToStateTransitionResults streaming endpoint

---

package-lock.json

package-lock.json contained not patched protobufjs
package-lock.json was regenerated

fix: lock file contained not patched protobufjs

---

clients/core/v0/objective-c/Core.pbobjc.h
clients/core/v0/objective-c/Core.pbobjc.m
clients/core/v0/python/core_pb2.py
protos/core/v0/core.proto

fix: revert "feat: restructure core status response"

---

CHANGELOG.md
package-lock.json
package.json

Release 0.19.0
- Update changelog
- Bump version to 0.19.0
None
None

 chore(release): update changelog and bump version 0.19.0

---

clients/platform/v0/objective-c/Platform.pbobjc.h
clients/platform/v0/objective-c/Platform.pbobjc.m
clients/platform/v0/python/platform_pb2.py
protos/platform/v0/platform.proto

In order to have more data an additional set of proofs were added to `Proof` message
- added `app hash`, `height`,  `chain locked core height`,  `quorum hash`, `signature`
Unit tests
None

feat: add an additional set of fields for proofs

---

clients/core/v0/objective-c/Core.pbobjc.h
clients/core/v0/objective-c/Core.pbobjc.m
clients/core/v0/python/core_pb2.py
protos/core/v0/core.proto

To be able to provide more information along with the transaction in `DAPI` additional fields were added to `GetTransactionResponse`
- updated `GetTransactionResponse`
Unit tests
None.

feat: add additional information to `GetTransactionResponse`

---

clients/core/v0/objective-c/Core.pbobjc.h
clients/core/v0/objective-c/Core.pbobjc.m
clients/core/v0/python/core_pb2.py
protos/core/v0/core.proto

`block_hash` field was named incorrectly
- renamed field
None.

fix: block hash field was named incorrectly

---

.github/workflows/test_and_release.yml

The satackey cache action does not give appreciable benefits when not building our own images.
- Remove satackey cache action
In CI

ci: remove satackey cache action

---

package-lock.json
package.json

grpc-common version was updated
Update grpc-common dep version
In CI

chore: bump grpc-common version

---

.github/workflows/test_and_release.yml
clients/core/v0/nodejs/core_protoc.js
clients/core/v0/web/core_pb.js
clients/platform/v0/nodejs/platform_protoc.js
clients/platform/v0/web/platform_pb.js
package-lock.json
package.json
scripts/build.sh

We need to update to node 16
- Update package to node 16
- Run tests
- Update build script to use alternative Docker image
- Run builds
- Update CI
In CI
None

chore: update package to node 16

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.9

chore: bump version to 0.21.0-dev.9

---

.github/workflows/test_and_release.yml
package-lock.json
package.json

Release was failing with `git@github.com: Permission denied (publickey).`
Force use of HTTPS to pull from external github repos
In CI
None

ci: fix github ssh error

---

package-lock.json
package.json

The `grpc-common` dep needed to be incremented to fix a bug in CI relating to pulling via git+ssh
Increment version
In CI
None

chore: bump grpc-common dep to 0.5.2

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.10

chore: bump version to 0.21.0-dev.10

---

package-lock.json
package.json

The `grpc-common` dep needed to be incremented to fix a bug in CI relating to pulling via git+ssh
Increment version
In CI
None

chore: bump grpc-common dep to 0.5.3 and fix npm replacement of +ssh

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.11

chore: bump version to 0.21.0.dev 11

---

package-lock.json
package.json

Builds were failing due to SSH errors or SHA conflicts with the protobuf dep
Revert to standard `github:` syntax to install the dep
In CI
None

chore: fix protobuf dep

---

package-lock.json
package.json

Bump version for release
Bump version to 0.21.0-dev.11

chore: bump version to 0.21.0-dev.12

---

.github/workflows/test_and_release.yml

git was failing with `git@github.com: Permission denied (publickey).`
Force using NPM 7 instead of  NPM 6
In CI

ci: force npm 7 for release

---

README.md

This PR documents usage for CorePromiseClient and PlatformPromiseClient
N/A
N/A

docs: provide usage of CorePromiseClient and PlatformPromiseClient

---

package-lock.json
package.json

Version bump
Update package.json and package-lock.json

chore(master): bump version to v0.21.1
